
service: my-project-backend
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x

functions:
  activities:
    handler: handler.app
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http:
          method: get
          path: activities
          cors: true
    
        