
service: my-project-backend
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x

functions:
  activities:
    handler: handler.app
    events:
      - http:
          method: get
          path: activities
          cors: true
  